### PR TITLE
Updating dinner recipe

### PR DESCRIPTION
**Pull request by Justinli90**
## 🎯 Objective

Discuss dinner recipe with teammates

## 🛠️ Changes made

Adding ingredients and instructions to Dinner recipe🤩🤩

## 👥 Who needs to review this Pull Request? 

@ccastilloux @lancebarnardberkeley

### CODE REVIEW

**Comment by ccastilloux** [comment]
@Justinli90 Could we add into the recipe to make rice?

**Comment by lancebarnardberkeley** [comment]
this is really detailed. great job @Justinli90

**Comment by Justinli90** [comment]
> @Justinli90 Could we add into the recipe to make rice?

@ccastilloux absolutely! adding rice now

**Comment by Justinli90** [comment]
> this is really detailed. great job @Justinli90

Thanks @lancebarnardberkeley !!

**Comment by ccastilloux** [comment]
Updated the rice cooking instructions and allowed for brown rice as well 🤛

**Comment by Justinli90** [comment]
> Updated the rice cooking instructions and allowed for brown rice as well 🤛

NICE!! 🤜

**Comment by Justinli90** [comment]
Saw that you added the last step to cook the rice @Aleixsc 

Thanks! We totally forgot

**Comment by Justinli90** [comment]
@lancebarnardberkeley @ccastilloux @Aleixsc If changes look good to you all, I will merge the PR. Thanks! 👊💪

**Comment by Aleixsc** [comment]
Everything looks fantastic, thank you!

**Comment by ccastilloux** [comment]
@lancebarnardberkeley @Justinli90 @Aleixsc Looks good to me as well 👍

**Comment by Justinli90** [comment]
merging, thanks!  👍 😄

**Pull request merged**
