### PR TITLE
Deli Lunch Recipe

### PR DESCRIPTION
**Pull request by lancebarnardberkeley**
## 🎯 Objective

Creating Lunch recipe and ingredients  :satisfied: :satisfied:

## 🛠️ Changes made

Added lunch ingredients

## 👥 Who needs to review this Pull Request? 
@ccastilloux @Justinli90 @stalerat 
_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by Justinli90** [comment]
@ccastilloux  @lancebarnardberkeley I'm allergic to mayo. Can we do mustard instead?  🥺😭

**Comment by ccastilloux** [comment]
@lancebarnardberkeley Could we think about making cheese optional?

**Comment by Justinli90** [comment]
> @lancebarnardberkeley Could we think about making cheese optional?

yes please!

**Comment by lancebarnardberkeley** [comment]
> @ccastilloux @lancebarnardberkeley I'm allergic to mayo. Can we do mustard instead? 🥺😭

sure, no problem. changing now.

**Comment by Justinli90** [comment]
@lancebarnardberkeley @ccastilloux I just had a great idea! Adding option for sourdough bread now

**Review by Aleixsc — CHANGES_REQUESTED** [review]
Can we add a spoon in the Equipment section in case the mustard comes in a glass pot.

**Comment by Aleixsc** [comment]
For the rest it looks delicious great job guys

**Comment by Justinli90** [comment]
> Can we add a spoon in the Equipment section in case the mustard comes in a glass pot.

@Aleixsc sure go ahead. Great suggestion. Thanks!

**Comment by Justinli90** [comment]
@lancebarnardberkeley @ccastilloux @Aleixsc If changes look good to you all, I will merge the PR. Thanks! 👊💪

**Comment by Aleixsc** [comment]
All looks good to me, thanks for the great job team!

**Comment by Justinli90** [comment]
approved from my side as well 👍 😄

**Pull request merged**
